### ISSUE TITLE
Roundtrip WebDriverAgent bundle

### ISSUE THREAD

**Issue by qmfrederik** [filipnavara/CodeSign#13]
Being able to code sign the Facebook / Appium WebDriverAgent is an important use case for me.  It will drive most of the contributions I'll be making to the CodeSign project.

Ideally, CodeSign can roundtrip the WebDriverAgent bundle: you feed it a signed copy of WebDriverAgent, with the same code signing certificate, identity and signing date, and you get an exact copy of that bundle back.

**Comment by qmfrederik** [comment]
#17, #18 and #19 combined allow me to roundtrip the main WebDriverAgent executable.  I'll put up a PR with a unit test once all these inidivual PRs are merged.

**Comment by filipnavara** [comment]
Great work! I will try to review everything in the coming days.

**Comment by filipnavara** [comment]
Related PRs are merged. Should we close this, or is there anything left to track?
